const STORAGE = 'lottery-count-v3';
const startingTickets = Array.from({length:42}, (_, i) => ({name:`Ticket ${i+1}`, price: i < 3 ? 1 : i < 11 ? 2 : i < 19 ? 5 : i < 29 ? 10 : i < 36 ? 20 : i < 40 ? 30 : i === 40 ? 50 : 10}));
if (new URLSearchParams(window.location.search).has('new')) localStorage.removeItem(STORAGE);
const state = JSON.parse(localStorage.getItem(STORAGE) || 'null') || { tickets: startingTickets, entries:{}, details:{}, registerCash:'', siteUrl:'' };
const $ = id => document.getElementById(id);
const money = value => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value)||0);
const save = () => localStorage.setItem(STORAGE, JSON.stringify(state));
function localDate(){const now=new Date();const offset=now.getTimezoneOffset()*60000;return new Date(now-offset).toISOString().slice(0,10)}
function updateReportDay(){const value=$('reportDate').value;if(!value)return;$('reportDay').textContent=new Date(`${value}T12:00:00`).toLocaleDateString(undefined,{weekday:'long'})}
$('reportDate').value = localDate();
$('reportDate').onchange = updateReportDay;
updateReportDay();

function ticketMax(index){return index<3?199:index<11?99:index<29?49:29}
function ticketStats(index){const row=state.tickets[index],entry=state.entries[index]||{},openText=String(entry.open??'').trim(),closeText=String(entry.close??'').trim(),max=ticketMax(index),isNumber=value=>/^\d+$/.test(value),inRange=value=>Number(value)>=0&&Number(value)<=max;if(openText==='-'&&closeText==='-')return {sold:0,amount:0,invalid:false,emptyBook:true,max};if(openText===''&&closeText==='')return {sold:0,amount:0,invalid:false,max};if(isNumber(openText)&&closeText==='-'){if(!inRange(openText))return {sold:0,amount:0,invalid:true,message:`Numbers must be from 0 to ${max}.`,max};const sold=max-Number(openText);return {sold,amount:sold*(Number(row.price)||0),invalid:false,max};}if(openText==='-'&&isNumber(closeText)){if(!inRange(closeText))return {sold:0,amount:0,invalid:true,message:`Numbers must be from 0 to ${max}.`,max};const sold=Number(closeText);return {sold,amount:sold*(Number(row.price)||0),invalid:false,max};}if(!isNumber(openText)||!isNumber(closeText))return {sold:0,amount:0,invalid:true,message:'Use whole numbers, or − for a book transition.',max};const open=Number(openText),close=Number(closeText);if(open>max||close>max)return {sold:0,amount:0,invalid:true,message:`Numbers must be from 0 to ${max}.`,max};if(close<open)return {sold:0,amount:0,invalid:true,message:'Closing number must be the same as or greater than opening number.',max};const sold=close-open;return {sold,amount:sold*(Number(row.price)||0),invalid:false,max};}
function renderTickets(){const list=$('ticketList');list.innerHTML='';const unpriced=state.tickets.some(t=>!Number(t.price));$('priceNotice').classList.toggle('hidden',!unpriced);$('priceNotice').textContent='Some ticket prices are not set yet. Tap settings to add them before counting.';state.tickets.forEach((ticket,index)=>{const node=$('ticketTemplate').content.cloneNode(true),stats=ticketStats(index);node.querySelector('.ticket-name').textContent=ticket.name||`Ticket ${index+1}`;node.querySelector('.ticket-price').textContent=Number(ticket.price)?`${money(ticket.price)} each · numbers 0–${stats.max}`:'Price not set';node.querySelector('.ticket-amount').textContent=money(stats.amount);node.querySelector('.ticket-sold').textContent=stats.emptyBook?'No tickets':`${stats.sold} sold`;const error=node.querySelector('.ticket-error');if(stats.invalid){error.textContent=stats.message;error.classList.remove('hidden')}const opening=node.querySelector('.opening'),closing=node.querySelector('.closing');opening.value=(state.entries[index]||{}).open??'';closing.value=(state.entries[index]||{}).close??'';[opening,closing].forEach((input)=>{input.type='text';input.removeAttribute('min');input.oninput=()=>{state.entries[index]=state.entries[index]||{};state.entries[index][input===opening?'open':'close']=input.value;save();renderTickets();renderFinance()}});node.querySelector('.no-tickets').onclick=()=>{state.entries[index]={open:'-',close:'-'};save();renderTickets();renderFinance()};list.append(node)});updateTotals();}
function updateTotals(){let sales=0;state.tickets.forEach((_,i)=>{const x=ticketStats(i);sales+=x.amount});$('financeLotteryTotal').textContent=money(sales);return sales}
function renderFinance(){const sales=updateTotals(),box=$('adjustmentList');box.innerHTML='';const details=[['instances1','Instances 1',-1],['instances2','Instances 2',-1],['sales1','Sales 1',1],['sales2','Sales 2',1],['cashes1','Cashes 1',-1],['cashes2','Cashes 2',-1],['pullTabs','Pull tabs',-1]];let detailTotal=0;details.forEach(([key,label,sign])=>{const amount=Number(state.details[key])||0;detailTotal+=sign*amount;const row=document.createElement('div');row.className='adjustment detail-row';row.innerHTML=`<label for="${key}">${label}</label><div class="money-input"><span>$</span><input id="${key}" aria-label="${label}" inputmode="decimal" enterkeyhint="next" type="number" min="0" step="0.01" placeholder="0.00"></div>`;const input=row.querySelector('input');input.value=state.details[key]||'';input.oninput=()=>{state.details[key]=input.value;save();renderFinance()};box.append(row)});const expected=sales+detailTotal;$('expectedCash').textContent=money(expected);$('difference').textContent='Scratch off sales − instances + sales − cashes − pull tabs'; }
function renderSettings(){const editor=$('priceEditor');editor.innerHTML='';state.tickets.forEach((t,i)=>{const row=document.createElement('div');row.className='price-row';row.innerHTML=`<input aria-label="Ticket name" placeholder="Ticket name"><input aria-label="Ticket price" inputmode="decimal" type="number" min="0" step="0.01" placeholder="Price"><button class="remove" type="button" aria-label="Remove ticket">×</button>`;const [name,price,remove]=row.children;name.value=t.name||'';price.value=t.price||'';name.oninput=()=>{t.name=name.value;save()};price.oninput=()=>{t.price=price.value;save()};remove.onclick=()=>{state.tickets.splice(i,1);save();renderSettings()};editor.append(row)});$('siteUrl').value=state.siteUrl||'';showQr()}
function showQr(){const url=$('siteUrl').value.trim(),area=$('qrArea');if(url){$('qrImage').src=`https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(url)}`;area.classList.remove('hidden')}else area.classList.add('hidden')}
$('settingsButton').onclick=()=>{$('settingsDialog').showModal();renderSettings()};
$('addTicket').onclick=()=>{state.tickets.push({name:`Ticket ${state.tickets.length+1}`,price:''});save();renderSettings()};
$('siteUrl').oninput=showQr;$('saveSettings').onclick=()=>{state.siteUrl=$('siteUrl').value.trim();save();renderTickets();renderFinance()};
$('saveReport').onclick=()=>{save();const button=$('saveReport'),old=button.textContent;button.textContent='✓ Report saved on this device';setTimeout(()=>button.textContent=old,1800)};
$('printReport').onclick=()=>window.print();
document.addEventListener('keydown',event=>{if(event.key!=='Enter')return;const fields=[...document.querySelectorAll('.ticket-list input, #adjustmentList input')];const current=fields.indexOf(event.target);if(current<0)return;event.preventDefault();fields[current+1]?.focus()});
renderTickets();renderFinance();
